/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // main: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  main: [

    {
      type: "category",
      label: "About",
      items: [
        "about/welcome",
        "about/architecture",
        "about/security",
        "about/roadmap",
        "about/case-studies",
        "about/comparison",
      ],
      link: {
        type: "generated-index",
        title: "About BrowZer",
        description: "The sections below introduce you to BrowZer by breaking it down piece by piece.",
        slug: "/about",
      },
    },

    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/idp",
        "getting-started/ziti-console",
        "getting-started/ziti-http-agent",
        "getting-started/ziti-external-jwt-signer",
        "getting-started/ziti-auth-policies",
        "getting-started/ziti-identities",
      ],
      link: {
        type: "generated-index",
        title: "Getting Started with OpenZiti BrowZer",
        description: "Follow the sequence of steps outlined in the sections below.",
        slug: "/getting-started",
      },
    },

    {
      type: "category",
      label: "FAQ",
      items: [
        "faq/faq-general",
        "faq/faq-http-agent",
        "faq/faq-runtime",
      ],
      link: {
        type: "generated-index",
        title: "FAQ",
        description: "Below are various categories we see questions falling into.",
        slug: "/faq",
      },
    },

    "troubleshooting",

    {
      type: "category",
      label: "Community",
      items: [
        "community/contributing",
      ],
      link: {
        type: "generated-index",
        title: "Community",
        description: "How to be a part of the OpenZiti BrowZercommunity",
        slug: "/community",
      },
    },

  ],
  
};

module.exports = sidebars;
