/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // main: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  main: [
    {
      type: "category",
      label: "About",
      items: [
        "about/what-is-browzer",
        "about/architecture",
        "about/security",
        "about/roadmap",
        "about/case-studies",
        "about/comparison",
      ],
      link: {
        type: "generated-index",
        title: "About BrowZer",
        description: "About BrowZer",
        slug: "/about",
      },
    },

    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/idp",
        "getting-started/ziti-console",
        "getting-started/ziti-http-agent",
        "getting-started/ziti-external-jwt-signer",
        "getting-started/ziti-auth-policies",
        "getting-started/ziti-identities",
      ],
      link: {
        type: "generated-index",
        title: "Getting Started with OpenZiti BrowZer Open Source",
        description: "Getting Started with OpenZiti BrowZer Open Source",
        slug: "/getting-started",
      },
    },

    "faq",
    "troubleshooting",
  ],
  
};

module.exports = sidebars;
