/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PcapPlusPlus",
  "tagline": "A multi-platform C++ library for capturing, parsing and crafting of network packets. It is designed to be efficient, powerful and easy to use.",
  "url": "https://pcapplusplus.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/logo/logo_icon_large.ico",
  "organizationName": "seladb",
  "projectName": "pcapplusplus.github.io",
  "trailingSlash": false,
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/curt/Repos/nf/github/ziti-browzer-doc/sidebars.js",
          "editUrl": "https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/"
        },
        "theme": {
          "customCss": "/Users/curt/Repos/nf/github/ziti-browzer-doc/src/css/custom.css"
        },
        "googleAnalytics": {
          "trackingID": "UA-74037205-2",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "algolia": {
      "appId": "31QB400Q4J",
      "apiKey": "bbfc76b67598a3116274ce4a735c143b",
      "indexName": "pcapplusplus",
      "contextualSearch": true,
      "searchPagePath": "search",
      "searchParameters": {}
    },
    "navbar": {
      "logo": {
        "alt": "PcapPlusPlus",
        "src": "img/logo/logo_color.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "quickstart",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "doc",
          "docId": "features",
          "position": "left",
          "label": "Features"
        },
        {
          "type": "doc",
          "docId": "api",
          "position": "left",
          "label": "API"
        },
        {
          "to": "/community",
          "label": "Community",
          "position": "left"
        },
        {
          "type": "docsVersionDropdown",
          "position": "left",
          "dropdownActiveClassDisabled": true,
          "dropdownItemsAfter": [
            {
              "to": "/versions",
              "label": "All versions"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://groups.google.com/d/forum/pcapplusplus-support",
          "position": "right",
          "label": "Google Group",
          "title": "PcapPlusPlus Google Group"
        },
        {
          "href": "mailto:pcapplusplus@gmail.com",
          "position": "right",
          "label": "Email",
          "title": "Send us an email"
        },
        {
          "href": "https://stackoverflow.com/questions/tagged/pcapplusplus",
          "position": "right",
          "label": "StackOverflow",
          "title": "PcapPlusPlus tag on StackOverflow"
        },
        {
          "href": "https://twitter.com/seladb",
          "position": "right",
          "label": "Twitter",
          "title": "PcapPlusPlus on Twitter"
        },
        {
          "href": "https://github.com/seladb/PcapPlusPlus",
          "position": "right",
          "label": "GitHub",
          "title": "PcapPlusPlus on GitHub"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Installation",
              "to": "/docs/install"
            },
            {
              "label": "Features",
              "to": "/docs/features"
            },
            {
              "label": "Tutorials",
              "to": "/docs/tutorials"
            },
            {
              "label": "DPDK",
              "to": "/docs/dpdk"
            },
            {
              "label": "Example Apps",
              "to": "/docs/examples"
            },
            {
              "label": "API Documentation",
              "to": "/docs/api"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/seladb/PcapPlusPlus"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/seladb"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/pcapplusplus"
            },
            {
              "label": "Google Group",
              "href": "https://groups.google.com/d/forum/pcapplusplus-support"
            },
            {
              "label": "Email",
              "href": "mailto:pcapplusplus@gmail.com"
            },
            {
              "label": "Contribute",
              "to": "/community#contribute"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Releases",
              "to": "/versions"
            },
            {
              "label": "Benchmarks",
              "to": "/docs/benchmark"
            },
            {
              "label": "License",
              "to": "/docs/features/#license"
            },
            {
              "label": "Web-site GitHub Repo",
              "href": "https://github.com/PcapPlusPlus/pcapplusplus.github.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 seladb. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
